theme: jekyll-theme-minimal
title: Duy Tan Do
description: I am Tan, a PhD student at Universidad Carlos III de Madrid.
teaser: "/doduytan29.github.io/assets/img/500x300.png"
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
