theme: jekyll-theme-minimal
teaser: /assets/img/DuyTanDo.JPG # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
title: Duy Tan Do
description: I am Tan, a PhD student at Universidad Carlos III de Madrid.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
