theme: jekyll-theme-minimal
teaser: "favicon.png"
title: Duy Tan Do
description: I am Tan, a PhD student at Universidad Carlos III de Madrid.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
