theme: jekyll-theme-minimal
teaser: /assets/img/DuyTanDo.png # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
title: GitHub pages template
description: A simple template based on minimal jekyll theme
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
