theme: jekyll-theme-minimal
title: Duy Tan Do
description: I am Tan, a PhD student at Universidad Carlos III de Madrid. My research interests include corporate finance, governance and disclosure.

show_downloads: False
navigation:
  - title: Home
    url: /
  - title: CV
    url: setup

